apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-volumen
  namespace: proyectocicd
spec: 
  storageClassName: jenkins-master-volumen
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-master-volumen/
