apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-volumen
  namespace: proyectocicd
spec: 
  storageClassName: sonarqube-volumen
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/sonarqube-volumen/
